[CmdletBinding()]
param(
  [Parameter(Mandatory=$true)][string]$TransferRoot,
  [Parameter(Mandatory=$true)][string]$ExpectedManifestSha256,
  [Parameter(Mandatory=$true)][string]$ExpectedCustodySha256,
  [Parameter(Mandatory=$true)][string]$ExpectedVerificationSha256,
  [Parameter(Mandatory=$true)][string]$ReturnRoot
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$scriptRoot=$PSScriptRoot;$repositoryRoot=[IO.Path]::GetFullPath((Join-Path $scriptRoot '..\..\..'))
. (Join-Path $scriptRoot 'Oracle.Stage4R5CleanHostCore.ps1')
. (Join-Path $scriptRoot 'Oracle.Stage4R5LifecyclePolicy.ps1')
$contract=Get-Content -Raw -LiteralPath (Join-Path $scriptRoot 'Oracle.Stage4R5ExecutionContract.json')|ConvertFrom-Json
$transfer=Assert-OracleStage4R5Transfer $TransferRoot $ExpectedManifestSha256 $ExpectedCustodySha256 $ExpectedVerificationSha256
$return=[IO.Path]::GetFullPath($ReturnRoot);if(-not(Test-Path -LiteralPath $return -PathType Container)){throw 'R5 return root is absent.'}
$required=@('authority-record.json','provider-start-request.json','host-continuity.json','pre-authority.json','provider-admission.json','provider-teardown.json','qualification-terminal.json','qualification-host-return-manifest.json','qualification-host-attempt')
foreach($name in $required){if(-not(Test-Path -LiteralPath (Join-Path $return $name))){throw "R5 returned record is absent: $name"}}
if(Test-Path -LiteralPath (Join-Path $return 'provider-secret-handoff.json')){throw 'Secret handoff residue remains in the returned mission.'}
$authority=Get-Content -Raw -LiteralPath (Join-Path $return 'authority-record.json')|ConvertFrom-Json;$request=Get-Content -Raw -LiteralPath (Join-Path $return 'provider-start-request.json')|ConvertFrom-Json;$terminal=Get-Content -Raw -LiteralPath (Join-Path $return 'qualification-terminal.json')|ConvertFrom-Json;$teardown=Get-Content -Raw -LiteralPath (Join-Path $return 'provider-teardown.json')|ConvertFrom-Json
if(-not[bool]$authority.consumed-or[string]$authority.transferId-cne[string]$transfer.transferId-or[string]$request.authorityId-cne[string]$authority.authorityId-or[string]$terminal.attemptId-cne[string]$authority.attemptId-or[string]$teardown.attemptId-cne[string]$authority.attemptId){throw 'Returned mission identity continuity differs.'}
if([string]$terminal.result-cne'passed-awaiting-provider-teardown'){throw 'Qualification host did not pass; success closure is prohibited.'}
if([string]$teardown.result-cne'passed'-or-not[bool]$teardown.zeroResidue-or@($teardown.cleanupFailures).Count-ne0-or[int]$teardown.providerContainers-ne0-or[int]$teardown.providerVolumes-ne0-or[int]$teardown.providerNetworks-ne0-or[int]$teardown.providerRelays-ne0-or[int]$teardown.firewallRules-ne0-or[bool]$teardown.providerWorkRootPresent){throw 'Provider-host teardown is not zero residue.'}
$returnedAttempt=Join-Path $return 'qualification-host-attempt';$returnManifest=Get-Content -Raw -LiteralPath (Join-Path $return 'qualification-host-return-manifest.json')|ConvertFrom-Json;$actualReturn=@(Get-OracleStage4R5Inventory $returnedAttempt)
if([string]$returnManifest.attemptId-cne[string]$authority.attemptId-or[bigint]$actualReturn.Count-ne[bigint]@($returnManifest.files).Count-or(($actualReturn|ConvertTo-Json -Depth 8 -Compress)-cne(@($returnManifest.files)|ConvertTo-Json -Depth 8 -Compress))){throw 'Qualification-host return inventory differs.'}
$artifactBoundary=[IO.Path]::GetFullPath((Join-Path $repositoryRoot ([string]$contract.paths.artifactRoot)));if(-not(Test-Path -LiteralPath $artifactBoundary -PathType Container)){[IO.Directory]::CreateDirectory($artifactBoundary)|Out-Null}
$attemptRoot=Join-Path $artifactBoundary ([string]$authority.attemptId);if(Test-Path -LiteralPath $attemptRoot){throw 'Create-only source R5 attempt root already exists.'};[void](Copy-OracleStage4R5DirectoryCreateOnly $returnedAttempt $attemptRoot)
foreach($pair in @(@('provider-admission.json','logs\provider-admission.json'),@('provider-teardown.json','logs\provider-teardown.json'),@('qualification-terminal.json','logs\qualification-terminal.json'),@('qualification-host-return-manifest.json','logs\qualification-host-return-manifest.json'))){[IO.File]::Copy((Join-Path $return $pair[0]),(Join-Path $attemptRoot $pair[1]),$false)}
$lifecycle=@(Get-ChildItem -LiteralPath (Join-Path $attemptRoot 'lifecycle') -File|Sort-Object Name);if($lifecycle.Count-ne17){throw 'Returned qualification lifecycle must contain exactly phases 001 through 017.'}
$state=New-OracleStage4R5LifecycleState;foreach($file in $lifecycle){$record=Get-Content -Raw -LiteralPath $file.FullName|ConvertFrom-Json;[void](Move-OracleStage4R5Lifecycle $state ([string]$record.phase))}
function Publish-FinalLifecycle([string]$Phase,$Details){$number=@(Get-ChildItem -LiteralPath (Join-Path $attemptRoot 'lifecycle') -File).Count+1;Write-OracleStage4R5CreateOnlyJson (Join-Path $attemptRoot ("lifecycle\{0:d3}-{1}.json"-f$number,$Phase)) ([ordered]@{contract='oracle.sprint-30-5.stage-4-r5-lifecycle';authorityId=[string]$authority.authorityId;attemptId=[string]$authority.attemptId;phase=$Phase;recordedAtUtc=[DateTime]::UtcNow.ToString('o');details=$Details});[void](Move-OracleStage4R5Lifecycle $state $Phase)}
Publish-FinalLifecycle 'provider-torn-down' @{providerIdentity=[string]$teardown.providerIdentity;providerTeardownSha256=Get-OracleStage4R5Sha256 (Join-Path $return 'provider-teardown.json');zeroResidue=$true}
Publish-FinalLifecycle 'cleanup-passed' @{providerHostZeroResidue=$true;qualificationHostPackageResidue=0;qualificationHostTrustResidue=0;qualificationHostRelayResidue=0;secretHandoffResidue=0}
$immutable=Join-Path $attemptRoot 'immutable-evidence';if(Test-Path -LiteralPath $immutable){throw 'Immutable evidence root already exists.'};[IO.Directory]::CreateDirectory($immutable)|Out-Null
foreach($name in @('evidence','lifecycle','logs')){Copy-Item -LiteralPath (Join-Path $attemptRoot $name) -Destination (Join-Path $immutable $name) -Recurse -ErrorAction Stop}
$payloadItems=@(Get-OracleStage4R5Inventory $immutable);Write-OracleStage4R5CreateOnlyJson (Join-Path $immutable 'payload-manifest.json') ([ordered]@{contract='oracle.sprint-30-5.stage-4-r5-payload-manifest';authorityId=[string]$authority.authorityId;attemptId=[string]$authority.attemptId;files=$payloadItems})
$archive=Join-Path $attemptRoot 'Oracle.Sprint30.5.Stage4R5QualificationEvidence.zip';Add-Type -AssemblyName System.IO.Compression.FileSystem;[IO.Compression.ZipFile]::CreateFromDirectory($immutable,$archive,[IO.Compression.CompressionLevel]::Optimal,$false);$archiveHash=Get-OracleStage4R5Sha256 $archive
$sidecar="$archive.sha256.txt";$bytes=[Text.Encoding]::ASCII.GetBytes("$archiveHash  $(Split-Path -Leaf $archive)`n");$stream=[IO.File]::Open($sidecar,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$stream.Write($bytes,0,$bytes.Length);$stream.Flush($true)}finally{$stream.Dispose()}
Publish-FinalLifecycle 'evidence-frozen' @{archive=(Split-Path -Leaf $archive);archiveSha256=$archiveHash}
if(-not$state.terminal-or@($state.completed).Count-ne20){throw 'R5 lifecycle did not reach exactly twenty terminal phases.'}
Write-OracleStage4R5CreateOnlyJson (Join-Path $attemptRoot 'completion.json') ([ordered]@{schemaVersion='1.0.0';contract='oracle.sprint-30-5.stage-4-r5-completion';result='passed-awaiting-founder-review';authorityId=[string]$authority.authorityId;attemptId=[string]$authority.attemptId;transferId=[string]$transfer.transferId;archiveSha256=$archiveHash;requiredJourneys=10;requiredLifecyclePhases=20;zeroResidue=$true;retryAuthorised=$false;stage5Started=$false;completedAtUtc=[DateTime]::UtcNow.ToString('o')})
$finalItems=@(Get-OracleStage4R5Inventory $attemptRoot|Where-Object{$_.path-cne'final-evidence-manifest.json'});Write-OracleStage4R5CreateOnlyJson (Join-Path $attemptRoot 'final-evidence-manifest.json') ([ordered]@{schemaVersion='1.0.0';contract='oracle.sprint-30-5.stage-4-r5-final-evidence-manifest';result='passed-awaiting-founder-review';authorityId=[string]$authority.authorityId;attemptId=[string]$authority.attemptId;files=$finalItems})
$evidenceParent=[IO.Path]::GetFullPath((Join-Path $repositoryRoot ([string]$contract.paths.repositoryEvidenceRoot)));if(-not(Test-Path -LiteralPath $evidenceParent -PathType Container)){[IO.Directory]::CreateDirectory($evidenceParent)|Out-Null};$evidenceRoot=Join-Path $evidenceParent ([string]$authority.attemptId);if(Test-Path -LiteralPath $evidenceRoot){throw 'Create-only repository R5 evidence root already exists.'};[void](Copy-OracleStage4R5DirectoryCreateOnly $attemptRoot $evidenceRoot)
$sourceInventory=@(Get-OracleStage4R5Inventory $attemptRoot);$evidenceInventory=@(Get-OracleStage4R5Inventory $evidenceRoot);if(($sourceInventory|ConvertTo-Json -Depth 8 -Compress)-cne($evidenceInventory|ConvertTo-Json -Depth 8 -Compress)){throw 'Repository evidence reconciliation differs.'}
[pscustomobject][ordered]@{result='passed-awaiting-founder-review';transferId=[string]$transfer.transferId;authorityId=[string]$authority.authorityId;attemptId=[string]$authority.attemptId;attemptRoot=$attemptRoot;repositoryEvidence=$evidenceRoot;archiveSha256=$archiveHash;finalEvidenceManifestSha256=Get-OracleStage4R5Sha256 (Join-Path $attemptRoot 'final-evidence-manifest.json');zeroResidue=$true;retryAuthorised=$false}|ConvertTo-Json -Depth 8
