[CmdletBinding()]param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$root=$PSScriptRoot;$contract=Get-Content -Raw -LiteralPath (Join-Path $root 'Oracle.Stage4R5ExecutionContract.json')|ConvertFrom-Json
. (Join-Path $root 'Oracle.Stage4R5LifecyclePolicy.ps1')
. (Join-Path $root 'Oracle.Stage4R5NetworkPolicy.ps1')
. (Join-Path $root 'Oracle.Stage4R5JourneyPolicy.ps1')
. (Join-Path $root 'Oracle.Stage4R5ProviderHostPolicy.ps1')
. (Join-Path $root 'Oracle.Stage3R13ActivationPolicy.ps1')
function Assert-Rejected([scriptblock]$Action,[string]$Name){try{&$Action;throw "Hostile fixture was accepted: $Name"}catch{if($_.Exception.Message-ceq"Hostile fixture was accepted: $Name"){throw}}}
if([string]$contract.status-cne'founder-authorised-execution-enabled'-or-not[bool]$contract.executionAuthority.founderAuthorisedQualificationExecution-or-not[bool]$contract.executionAuthority.transferCreationPermitted-or-not[bool]$contract.executionAuthority.authorityCreationPermittedAfterAllPreAuthorityGates-or-not[bool]$contract.executionAuthority.qualificationAttemptPermitted){throw 'Execution authority is incomplete.'}
if([int]$contract.executionAuthority.maximumTransfers-ne1-or[int]$contract.executionAuthority.maximumAuthorities-ne1-or[int]$contract.executionAuthority.maximumAttempts-ne1-or[bool]$contract.executionAuthority.retryAfterConsumedAuthorityPermitted){throw 'Single-use mission limits differ.'}
if([string]$contract.acceptedPreparation.commit-cne'f78c8981a032c4274b1e586d1a1ed0baffdd5929'-or[string]$contract.package.sha256-cne'97bedef7bae989ac251e4866835591c63550311aef6b172cf5caf3b204a6e490'-or[string]$contract.acceptedChain.stage3.attemptId-cne'stage3-r13-20260806T162253957Z-b0cb2a17'){throw 'Accepted R8/R13/R5 bindings differ.'}
if(@($contract.requiredJourneys).Count-ne10-or@($contract.requiredLifecycle).Count-ne20){throw 'R5 acceptance inventory differs.'}
if([bool]$contract.hosts.provider.qualificationExecutionPermitted-or[bool]$contract.hosts.provider.packageInstallationPermitted-or[bool]$contract.hosts.qualification.repositoryPermitted-or[bool]$contract.hosts.qualification.developmentToolsPermitted){throw 'Split-host role boundary was weakened.'}
if([bool]$contract.network.internetPermitted-or[bool]$contract.network.defaultRoutesPermitted-or[bool]$contract.network.postgresRemoteAccessPermitted-or[bool]$contract.network.productionEndpointsPermitted-or(@($contract.network.providerPublications)-join',')-cne'54321,54324'){throw 'Network isolation contract differs.'}
[void](Assert-OracleStage4R5PrivateLink '192.168.70.1' '192.168.70.2' 30);[void](Assert-OracleStage4R5RelayPlan @($contract.network.qualificationRelays) '192.168.70.1')
Assert-Rejected {Assert-OracleStage4R5PrivateLink '192.168.70.1' '192.168.70.1' 30} 'same-host';Assert-Rejected {Assert-OracleStage4R5PrivateLink '192.168.70.1' '192.168.70.2' 16} 'prefix';Assert-Rejected {Assert-OracleStage4R5NoDefaultRoutes @([pscustomobject]@{destinationPrefix='0.0.0.0/0';state='active'}) 'provider-host'} 'default-route'
$state=New-OracleStage4R5LifecycleState;foreach($phase in @($contract.requiredLifecycle)){[void](Move-OracleStage4R5Lifecycle $state $phase)};if(-not$state.terminal-or@($state.completed).Count-ne20){throw 'Lifecycle did not terminate exactly.'};Assert-Rejected {$bad=New-OracleStage4R5LifecycleState;[void](Move-OracleStage4R5Lifecycle $bad 'baseline-verified')} 'phase-skip'
$journey=[pscustomobject][ordered]@{contract='oracle.sprint-30-5.stage-4-r5-journey';result='passed';classification='GOVERNED-STAGE-4-R5-QUALIFICATION';provider=[pscustomobject]@{classification='disposable-local-non-production';implementation='accepted-r4-supabase-stack-on-engineering-provider-host';productionEndpoint=$false;externalEmail=$false;splitHost=$true};journeys=@($contract.requiredJourneys|ForEach-Object{[pscustomobject]@{id=[string]$_;result='passed'}});rendering=[pscustomobject]@{protectedStatus=200;mainLandmarks=1;levelOneHeadings=1;method='authenticated-installed-package-server-render'};isolation=[pscustomobject]@{accountCount=2;crossAccountLeaks=0;distinctAuthenticatedPrincipals=$true;distinctOperators=$true;rlsBindingsPerPrincipal=@(1,1)};secretsRetained=$false}
[void](Assert-OracleStage4R5JourneyRecord $journey);Assert-Rejected{$bad=$journey|ConvertTo-Json -Depth 10|ConvertFrom-Json;$bad.provider.implementation='fixture';Assert-OracleStage4R5JourneyRecord $bad}'provider-fixture';Assert-Rejected{$bad=$journey|ConvertTo-Json -Depth 10|ConvertFrom-Json;$bad.isolation.crossAccountLeaks=1;Assert-OracleStage4R5JourneyRecord $bad}'cross-account-leak'
$provider=[pscustomobject][ordered]@{contract='oracle.sprint-30-5.stage-4-r5-provider-admission';result='passed';providerHost='DESKTOP-M3H22E4';providerIdentity='provider-stage4-r5-20260806T190000000Z-a1b2c3d4';network=[pscustomobject]@{activeDefaultRoutes=0;privateOnLinkOnly=$true;internetReachable=$false;postgresPublished=$false;publishedPorts=@(54321,54324)};provider=[pscustomobject]@{classification=[string]$contract.provider.classification;implementation=[string]$contract.provider.implementation;productionEndpoint=$false;externalEmail=$false};images=@($contract.provider.services.PSObject.Properties|ForEach-Object{[pscustomobject]@{image=[string]$_.Value.image;digest=[string]$_.Value.digest}});migrations=@($contract.provider.requiredMigrations);secretValuesRecorded=$false}
[void](Assert-OracleStage4R5ProviderAdmission $provider $contract);Assert-Rejected{$bad=$provider|ConvertTo-Json -Depth 10|ConvertFrom-Json;$bad.network.publishedPorts=@(54321,54322,54324);Assert-OracleStage4R5ProviderAdmission $bad $contract}'postgres-publication';Assert-Rejected{Assert-OracleStage4R5ProviderPublicRecordSecretFree '{"serviceKey":"secret"}'}'secret-field'
[void](Assert-OracleStage3R13ApplicationActivationContract $contract)
[pscustomobject][ordered]@{result='passed';classification=@('NON-QUALIFICATION','NON-AUTHORITY','NON-EVIDENCE','EXECUTION POLICY TEST');requiredJourneys=10;requiredLifecyclePhases=20;maximumTransfers=1;maximumAuthorities=1;maximumAttempts=1;retryAuthorised=$false;providerStateCreated=$false;relayStateCreated=$false;authorityCreated=$false;attemptCreated=$false}|ConvertTo-Json -Depth 5
